baseURL = "http://extrapolaciones.com"
title = "Extrapolaciones"
languageCode = "es"

theme = "theme"
themesDir = "./danielfrg.com"
summaryLength = 25

pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

[permalinks]
  articles = "/:year/:month/:title/"

[outputs]
home = [ "HTML", "RSS" ]

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
  tag = "tags"

[params]
  description = "Daniel Rodriguez website and blog about data science, apps and open source projects"
  keywords = "Daniel Rodriguez, danielfrg, Python, Data, Science, Kubernetes"
  author = "Daniel Rodriguez"
  index = "grid"

[menu]
  [[menu.header]]
    identifier = "twitter"
    name = "@danielfrg"
    url = "https://danielfrg.com"
    weight = 10
  [[menu.footer]]
    identifier = "home"
    name = "Inicio"
    url = "/"
    weight = 10
