baseURL = "http://extrapolaciones.com"
title = "Extrapolaciones"
languageCode = "es"

theme = "theme"
themesDir = "./danielfrg.com"
summaryLength = 25

pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

[permalinks]
  articles = "blog/:year/:month/:title/"

[outputs]
home = [ "HTML", "RSS" ]

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
  tag = "tags"

[params]
  description = "Extrapolaciones"
  keywords = "Extrapolaciones"
  author = "Yo"
  index = "grid"
  include_js = ["/dist/main.js"]
  include_css = ["/dist/index.css"]

[menu]
  # [[menu.header]]
  #   identifier = "twitter"
  #   name = "@danielfrg"
  #   url = "https://danielfrg.com"
  #   weight = 10
  [[menu.footer]]
    identifier = "home"
    name = "Inicio"
    url = "/"
    weight = 10
