title = "Extrapolaciones"
baseURL = "/"
languageCode = "es"
theme = "theme"
themesDir = "."
summaryLength = 25

pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

[permalinks]
  articles = "posts/:year/:month/:title/"

[outputs]
home = [ "HTML", "RSS" ]

[markup.goldmark.renderer]
unsafe = true

[params]
  author = "Daniel Rodriguez"
  description = ""

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Inicio"
    url = "/"
    weight = 10
#   [[menu.main]]
#     identifier = "about"
#     name = "About"
#     url = "/about/"
#     weight = 20
  [[menu.second]]
    identifier = "twitter"
    name = "@danielfrg"
    url = "https://twitter.com/danielfrg"
    weight = 10
  [[menu.footer]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/danielfrg"
    weight = 10
