name: extrapolaciones
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip

  # Development deps
  - pylint
  - flake8
  - black
  - isort

  # Other deps
  - ipykernel

  - pip:
      - notion
      - mistune==2.0.0a4
      - python-slugify
