name: extrapolaciones.com
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip

  # Dev tools
  - pylint
  - flake8
  - black
  - isort

  # Other deps
  - ipykernel

  - pip:
      # Articles
      # - notion
      - git+https://github.com/danielfrg/notion-py
      - mistune==2.0.0a4
      - python-slugify
