name: deploy

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]
        node-version: ["12"]
        hugo-version: ["0.74.2"]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - run: git fetch --prune --unshallow

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Print Python versions
        run: |
          which python
          which pip
          python --version
          pip --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip --version
          pip install -U -r requirements.txt
          # Temp fix for: https://github.com/jamalex/notion-py/issues/292
          pip install git+https://github.com/danielfrg/notion-py
          pip freeze

      - name: Make articles
        run: |
          make articles
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_TABLE_URL: ${{ secrets.NOTION_TABLE_URL }}

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install JS deps (Theme)
        run: |
          make theme-npm-install

      - name: Build theme
        run: |
          make theme

      - name: Setup Hugo ${{ matrix.hugo-version }}
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ matrix.hugo-version }}

      - name: Build docs
        run: |
          make hugo

      - name: Push docs (branch)
        uses: jsmrcaga/action-netlify-deploy@master
        if: github.event_name == 'pull_request'
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          build_directory: public

      - name: Push docs (master)
        uses: jsmrcaga/action-netlify-deploy@master
        if: (github.event_name != 'pull_request') && endsWith(github.ref, '/master')
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: public

      - name: Upload website
        uses: actions/upload-artifact@v1
        with:
          name: website
          path: public
