name: deploy

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          which python
          which pip
          python --version
          pip --version
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt
          # Temp fix:
          pip install git+https://github.com/c0j0s/notion-py
          pip freeze

      - name: Make articles
        run: |
          make articles
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_TABLE_URL: ${{ secrets.NOTION_TABLE_URL }}

      - name: Install node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: Install deps
        run: make npm-install

      - name: Build website
        run: |
          make npm-build

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.74.2"

      - name: Build docs
        run: |
          make hugo

      - name: Push docs (branch)
        uses: jsmrcaga/action-netlify-deploy@master
        if: github.event_name == 'pull_request'
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          build_directory: public

      - name: Push docs (master)
        uses: jsmrcaga/action-netlify-deploy@master
        if: (github.event_name != 'pull_request') && endsWith(github.ref, '/master')
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: public

      - name: Upload website
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: website
          path: public
